### ISSUE TITLE
maybe incompatible with 'structurify' mod

### ISSUE THREAD

**Issue by X-Machiavelli** [MaxenceDC/sparsestructures#40]
I'm guessing that this mod is incompatible with 'structurify' mod. because there doesn't seem to be any change in the spread of structures when the two mods are run together. Also, I'm not sure if it's a conflict between the two mods, but I sometimes experience huge server lag when new chunks are generated in the world. and soon my server stops working. what do you think about this issue? Or are the two mods unrelated to the issue and the others is causing the problem? For reference, the only mods installed on my server are those that add new structures. After reviewing the crash report and logs, it turns out to be a TPS lag on my server (>60 milliticks) caused by generating a new chunk. but I'm hosting a high-end server, so being suspicious of incompatibility between the two mods.

**Comment by MaxenceDC** [comment]
I mean sure they’re most probably incompatible with each other, but that’s because they do exactly the same thing to the game, in the same way. They’re not meant to be used together anyway, as they’re redundant. Why did you install both? Next update will take this incompatibility into account, if it detects the other mod.
